---
##
# AWS Code Build spec for building and deploying Hippo CMS
#

version: 0.1

phases:
  install:
    commands:
      # ERROR pls
      - echo "oh no!"
      - exit 1

artifacts:
  files:
    - "**/*"
