---
##
# AWS Code Build spec for building and deploying Hippo CMS
#

version: 0.1

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -qqy software-properties-common python-software-properties
      - apt-get install -qqy build-essential git awscli curl python-pip python-dev
      - pip install virtualenv

      # Java 8 install
      - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
      - add-apt-repository -y ppa:webupd8team/java
      - apt-get update
      - apt-get install -y oracle-java8-installer || echo "this should fail"
      - cd /var/lib/dpkg/info
        && sed -i 's|JAVA_VERSION=8u171|JAVA_VERSION=8u181|' oracle-java8-installer.*
        && sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/|PARTNER_URL=http://download.oracle.com/otn/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/|' oracle-java8-installer.*
        && sed -i 's|SHA256SUM_TGZ="b6dd2837efaaec4109b36cfbb94a774db100029f98b0d78be68c27bec0275982"|SHA256SUM_TGZ="1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3"|' oracle-java8-installer.*
        && sed -i 's|J_DIR=jdk1.8.0_171|J_DIR=jdk1.8.0_181|' oracle-java8-installer.*
      - apt-get install -y oracle-java8-installer maven
      # - rm -rf /var/lib/apt/lists/*
      - rm -rf /var/cache/oracle-jdk8-installer

      # SSH key
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa $HOME/.ssh/nhs-ci_rsa
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/nhs-ci_rsa.pub $HOME/.ssh/nhs-ci_rsa.pub
      - chmod 600 $HOME/.ssh/nhs-ci_rsa

      # Rundeck credentials
      - aws s3 cp s3://config.mgt.nhsd.io/codebuild/hippo_build/rd.password $HOME/rd.password

      # Add static.hosting.onehippo.com and github.com as known host
      - touch $HOME/.ssh/known_hosts
      - ssh-keygen -R static.hosting.onehippo.com
      - ssh-keyscan static.hosting.onehippo.com >> $HOME/.ssh/known_hosts
      - ssh-keygen -R github.com
      - ssh-keyscan github.com >> $HOME/.ssh/known_hosts

  build:
    commands:
      # Tag
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
        make version.bumpup"
      # Build
      - cd ci-cd && make clean build
      # Set git commit status
      - cd ci-cd && make github.status.success
      # Upload tgz files to various destinations
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa &&
        cd ci-cd && make ondemand.upload"
      # Deploy to Test Environment
      - . $HOME/rd.password && cd ci-cd && make ondemand.deploy
      # Push tag back to github
      - ssh-agent bash -c "
        ssh-add $HOME/.ssh/nhs-ci_rsa && cd ci-cd &&
        make git.update-environment-tag &&
        git push --tags"

artifacts:
  files:
    - "**/*"
