---
definitions:
  config:
    /hst:hosts:
      /dev-localhost:
        /localhost:
          /hst:root:
            /api:
              hst:alias: api
              hst:ismapped: false
              hst:namedpipeline: RestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /gdpr:
              hst:ismapped: false
              hst:namedpipeline: TargetingRestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /restapi:
              hst:alias: restapi
              hst:ismapped: false
              hst:namedpipeline: JaxrsRestPlainPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            hst:contextpath: ''
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            jcr:primaryType: hst:mount
          hst:scheme: http
          hst:showcontextpath: true
          hst:showport: true
          jcr:primaryType: hst:virtualhost
        hst:defaultport: 8080
        jcr:primaryType: hst:virtualhostgroup
      /dev-od:
        /io:
          /nhsd:
            /dev:
              /content:
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms-dev.nhsd.io'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      /internal:
        /127.0.0.1:
          /hst:root:
            /gdpr:
              hst:ismapped: false
              hst:namedpipeline: TargetingRestApiPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /restapi:
              hst:alias: restapi
              hst:ismapped: false
              hst:namedpipeline: JaxrsRestPlainPipeline
              hst:responseheaders:
              - 'Access-Control-Allow-Origin: *'
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            /restservices:
              hst:alias: restservices
              hst:ismapped: false
              hst:namedpipeline: JaxrsRestPlainPipeline
              hst:types:
              - rest
              jcr:primaryType: hst:mount
            hst:homepage: root
            hst:mountpoint: /hst:hst/hst:sites/common
            hst:responseheaders:
            - 'Strict-Transport-Security : max-age=31536000'
            - 'Content-Security-Policy: upgrade-insecure-requests'
            - 'Referrer-Policy: no-referrer-when-downgrade'
            - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
              payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
              magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
              execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
              ''none''; push ''self''; speaker *;  fullscreen *'
            jcr:primaryType: hst:mount
          hst:scheme: http
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      /prd:
        /uk:
          /nhs:
            /digital:
              /beta:
                /hst:root:
                  hst:mountpoint: /hst:hst/hst:sites/common
                  hst:nochannelinfo: true
                  jcr:primaryType: hst:mount
                jcr:primaryType: hst:virtualhost
              /content:
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms.digital.nhs.uk'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              /www:
                /hst:root:
                  /gdpr:
                    hst:ismapped: false
                    hst:namedpipeline: TargetingRestApiPipeline
                    hst:types:
                    - rest
                    jcr:primaryType: hst:mount
                  hst:mountpoint: /hst:hst/hst:sites/common
                  hst:nochannelinfo: true
                  jcr:primaryType: hst:mount
                jcr:primaryType: hst:virtualhost
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      /training-od:
        /io:
          /nhsd:
            /training:
              /content:
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms-training.nhsd.io'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      /tst:
        /io:
          /nhsd:
            /tst:
              /content:
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms-tst.nhsd.io'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      /uat:
        /io:
          /nhsd:
            /uat:
              /content:
                jcr:primaryType: hst:virtualhost
              /hst:root:
                /gdpr:
                  hst:ismapped: false
                  hst:namedpipeline: TargetingRestApiPipeline
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                /restapi:
                  hst:alias: restapi
                  hst:ismapped: false
                  hst:namedpipeline: JaxrsRestPlainPipeline
                  hst:responseheaders:
                  - 'Access-Control-Allow-Origin: https://cms-uat.nhsd.io'
                  hst:types:
                  - rest
                  jcr:primaryType: hst:mount
                hst:mountpoint: /hst:hst/hst:sites/common
                hst:responseheaders:
                - 'Strict-Transport-Security : max-age=31536000'
                - 'Content-Security-Policy: upgrade-insecure-requests'
                - 'Referrer-Policy: no-referrer-when-downgrade'
                - 'Feature-Policy: vibrate ''none''; microphone ''none''; camera ''none'';
                  payment ''none''; accelerometer ''none''; ambient-light-sensor ''none'';
                  magnetometer ''none''; midi ''none''; usb ''none''; wake-lock ''none'';
                  execution-while-out-of-viewport ''none''; sync-xhr ''self''; gyroscope
                  ''none''; push ''self''; speaker *;  fullscreen *'
                jcr:primaryType: hst:mount
              jcr:primaryType: hst:virtualhost
            jcr:primaryType: hst:virtualhost
          jcr:primaryType: hst:virtualhost
        jcr:primaryType: hst:virtualhostgroup
      hst:diagnosticsenabled: false
      hst:homepage: root
      hst:scheme: https
      hst:showcontextpath: false
      hst:showport: false
      jcr:primaryType: hst:virtualhosts
