brx.dataconnect.api.baseurl = https://api-staging.connect.bloomreach.com/dataconnect/api/v1/
brx.dataconnect.api.key = REDACTED
brx.dataconnect.accountId = 6405
brx.dataconnect.catalog = content_en

brx.dataconnect.transfer.connection.host = sftp-staging.connect.bloomreach.com
brx.dataconnect.transfer.connection.port = 22
brx.dataconnect.transfer.connection.location = home/digital_nhs_uk
brx.dataconnect.transfer.connection.username = digital_nhs_uk
brx.dataconnect.transfer.connection.privatekeypath = /Users/shaneahern/.ssh/contentserchkey
brx.dataconnect.transfer.connection.serverhostkey = REDACTED
brx.dataconnect.transfer.connection.connect.timeout = 60


