brx.dataconnect.api.baseurl = https://api-staging.connect.bloomreach.com/dataconnect/api/v1/
brx.dataconnect.api.key = [your DataConnect API key]
brx.dataconnect.accountId = [your brSM account id]
brx.dataconnect.catalog = content_en

brx.contentfeed.environment = dev-localhost
brx.dataconnect.transfer.connection.host = 192.168.178.20
brx.dataconnect.transfer.connection.port = 22
brx.dataconnect.transfer.connection.location = home/shaneahern
brx.dataconnect.transfer.connection.username = shaneahern
brx.dataconnect.transfer.connection.privatekeypath = /Users/shaneahern/.ssh/contentsearchkey
brx.dataconnect.transfer.connection.serverhostkey = REDACTED== 
brx.dataconnect.transfer.connection.connect.timeout = 60


