name: Convert new PRs to draft

on:
  pull_request:
    types: [opened]

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Convert to draft
        run: |
          gh pr ready ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --undo

      - name: Add Instructional Comment
        run: |
          gh pr review ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --request-changes \
            --body-file "pr_ready_body.md"
