name: Sechedule UAT Index Check

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - DW-0000-index-check

jobs:
  build:
    name: UAT - Request Sechedule Job
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Deploy request
        id: pipeline-deploy
        run: |
          make ondemand.pipeline-deploy > pipeline-deploy-output.txt
          echo "::set-output name=PIPELINE_DEPLOY_URL::"$(cat pipeline-deploy-output.txt | grep -Po "(?<=<)[^>]+")
        env:
          ENV: "uat"
          RD_URL: ${{ secrets.RD_API }}
          RD_USER: ${{ secrets.RD_USER }}
          RD_PASSWORD: ${{ secrets.RD_PASSWORD }}
