name: Sechedule UAT Index Check

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - DW-0000-index-check

jobs:
  build:
    name: UAT - Request Sechedule Job
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      #
      # Checkout the branch
      #
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Sechedule UAT
        id: pipeline-deploy
        run: |
          make ondemand.index-consistency-check-uat
        env:
          ENV: "uat"
          RD_URL: ${{ secrets.RD_API }}
          RD_USER: ${{ secrets.RD_USER }}
          RD_PASSWORD: ${{ secrets.RD_PASSWORD }}

